name: CICD_Assignment2
on:
  push:
    #types: [published]
jobs:
  Push_To_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from github repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
     
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}